### ISSUE TITLE
cannot install please help 'Cannot find module \'@ronomon/crypto-async\

### ISSUE THREAD

**Issue by shamar112** [MAGOWARE/backoffice-administration#100]
I tried several times to install but getting the same error below, using ubuntu 20.

ubuntu@vps-d9745ffc:~/backoffice-administration-master$ sudo node server.js
-------------------------------------Starting server----------------------------------------------------
2020-09-19T15:42:31.021Z - info: Initializing Sequelize...
2020-09-19T15:42:31.486Z - info: Finished Connecting to Database
2020-09-19T15:42:31.496Z - info: Initializing Stack...
2020-09-19T15:42:31.620Z - info: Redis server started
2020-09-19T15:42:31.628Z - info: Initializing LocalVariables...
2020-09-19T15:42:31.628Z - info: Initializing Middleware...
2020-09-19T15:42:31.634Z - info: Initializing ViewEngine...
2020-09-19T15:42:31.635Z - info: Initializing Modules Configuration...
2020-09-19T15:42:31.647Z - info: Initializing Helmet Headers...
2020-09-19T15:42:31.648Z - info: Initializing Modules Client Routes...
2020-09-19T15:42:31.649Z - info: Initializing Modules Server Policies...
2020-09-19T15:42:31.650Z - info: Initializing Modules Server Routes...
2020-09-19T15:42:31.678Z - error: Error starting redis server
{ message: 'Cannot find module \'@ronomon/crypto-async\'',
  stack:
   'Error: Cannot find module \'@ronomon/crypto-async\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/home/ubuntu/backoffice-administration-master/modules/deviceapiv2/server/auth/apiv2.server.auth.js:5:17)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/home/ubuntu/backoffice-administration-master/modules/analytics/server/routes/apiv2.events.server.routes.js:7:16)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)',
  code: 'MODULE_NOT_FOUND' }

**Comment by malforsaja** [comment]
@shamar112 which version of Node.js you are using?
