### ISSUE TITLE
Login from android client error : Cannot read property 'id' of null

### ISSUE THREAD

**Issue by PHHENS** [MAGOWARE/backoffice-administration#105]
Dear developper,
I've magoware portal up and running, created a new customer, but got database error on
android client (apk included in git) when try to log in : 

2021-01-22T09:46:51.361Z - error: device upsert error :  Cannot read property 'id' of null 
 TypeError: Cannot read property 'id' of null
    at addDefaultMediaPlayer (/usr/local/src/magoware/modules/deviceapiv2/server/controllers/credentials.server.controller.js:567:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
POST /apiv2/credentials/login 200 151 - 42.562 ms

In advance, thanks for your help.

**Comment by malforsaja** [comment]
@PHHENS please retrieve the latest code and run the migrations.

**Comment by PHHENS** [comment]
Troubles with subscriptions :
Server Side : subscription appears when editing user, but not in
subscription menu.
Client Side :  No subscription (cancel or buy subscription)

hope to have something work ... maybe ... one day ...


Le vendredi 26 février 2021 à 12:53 -0800, Malfor Saja a écrit :
