### ISSUE TITLE
Installation crashes

### ISSUE THREAD

**Issue by wanman** [MAGOWARE/backoffice-administration#17]
-------------------------------------Starting server----------------------------------------------------
2018-06-06T19:38:27.729Z - info: Initializing Sequelize...
2018-06-06T19:38:29.228Z - info: Finished Connecting to Database
2018-06-06T19:38:29.229Z - info: Initializing Stack...
2018-06-06T19:38:29.232Z - info: Initializing LocalVariables...
2018-06-06T19:38:29.234Z - info: Initializing Middleware...
2018-06-06T19:38:29.298Z - info: Initializing ViewEngine...
2018-06-06T19:38:29.298Z - info: Initializing Session...
2018-06-06T19:38:29.308Z - info: Initializing Modules Configuration...
2018-06-06T19:38:29.328Z - info: Initializing Helmet Headers...
2018-06-06T19:38:29.329Z - info: Initializing Modules Client Routes...
2018-06-06T19:38:29.329Z - info: Initializing Modules Server Policies...
2018-06-06T19:38:29.629Z - info: Initializing Modules Server Routes...
2018-06-06T19:38:30.807Z - info: Initializing Languages ...
2018-06-06T19:38:30.807Z - info: Initializing Error Routes...
2018-06-06T19:38:30.808Z - info: Initializing Socket.io...
Running HTTP server
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at /home/user/backoffice-administration-master/config/lib/app.js:26:9
    at Object.init (/home/user/backoffice-administration-master/config/lib/app.js:15:17)
    at Object.start (/home/user/backoffice-administration-master/config/lib/app.js:23:9)
    at /home/user/backoffice-administration-master/server.js:91:22
    at /home/user/backoffice-administration-master/node_modules/async/dist/async.js:473:16
    at next (/home/user/backoffice-administration-master/node_modules/async/dist/async.js:5329:29)
    at /home/user/backoffice-administration-master/node_modules/async/dist/async.js:969:16
    at /home/user/backoffice-administration-master/server.js:85:9
    at nextTask (/home/user/backoffice-administration-master/node_modules/async/dist/async.js:5324:14)
    at next (/home/user/backoffice-administration-master/node_modules/async/dist/async.js:5331:9)
    at /home/user/backoffice-administration-master/node_modules/async/dist/async.js:969:16
root@greens:/home/user/backoffice-administration-master#

**Comment by Sonofmarske** [comment]
I Have Exactly the same problem

---------------------------------------------------------------------
2018-06-10T16:55:59.724Z - info: Initializing Sequelize...
2018-06-10T16:56:03.372Z - info: Finished Connecting to Database
2018-06-10T16:56:03.373Z - info: Initializing Stack...
2018-06-10T16:56:03.374Z - info: Initializing LocalVariables...
2018-06-10T16:56:03.376Z - info: Initializing Middleware...
2018-06-10T16:56:03.563Z - info: Initializing ViewEngine...
2018-06-10T16:56:03.564Z - info: Initializing Session...
2018-06-10T16:56:03.580Z - info: Initializing Modules Configuration...
2018-06-10T16:56:03.628Z - info: Initializing Helmet Headers...
2018-06-10T16:56:03.630Z - info: Initializing Modules Client Routes...
2018-06-10T16:56:03.631Z - info: Initializing Modules Server Policies...
2018-06-10T16:56:04.602Z - info: Initializing Modules Server Routes...
2018-06-10T16:56:08.463Z - info: Initializing Languages ...
2018-06-10T16:56:08.464Z - info: Initializing Error Routes...
2018-06-10T16:56:08.464Z - info: Initializing Socket.io...
Running HTTP server
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3307
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at C:\Users\User\Desktop\backoffice-administration-master\config\lib\app.js:26:9
    at Object.init (C:\Users\User\Desktop\backoffice-administration-master\config\lib\app.js:15:17)
    at Object.start (C:\Users\User\Desktop\backoffice-administration-master\config\lib\app.js:23:9)
    at C:\Users\User\Desktop\backoffice-administration-master\server.js:91:22
    at C:\Users\User\Desktop\backoffice-administration-master\node_modules\async\dist\async.js:473:16
    at next (C:\Users\User\Desktop\backoffice-administration-master\node_modules\async\dist\async.js:5329:29)
    at C:\Users\User\Desktop\backoffice-administration-master\node_modules\async\dist\async.js:969:16
    at C:\Users\User\Desktop\backoffice-administration-master\server.js:85:9
    at nextTask (C:\Users\User\Desktop\backoffice-administration-master\node_modules\async\dist\async.js:5324:14)
    at next (C:\Users\User\Desktop\backoffice-administration-master\node_modules\async\dist\async.js:5331:9)
    at C:\Users\User\Desktop\backoffice-administration-master\node_modules\async\dist\async.js:969:16

**Comment by saimirg** [comment]
Error: listen EADDRINUSE :::80
Error: listen EADDRINUSE :::3307

It means that the port is being used by some other service. Please either stop the service occupying the port, or start MAGOWARE on another port. Will make this error message more understandable on next release.

**Comment by wanman** [comment]
Any idea on how to change ports? 

 AFter testing we found that your install fails on a linux LAMP install, just FYI, still.

**Comment by saimirg** [comment]
Please edit file /config/env/default.js nand change the following row
` port: process.env.PORT || 80,`

**Comment by graseuser** [comment]
> 2019-10-09T14:24:45.991Z - info: Initializing Sequelize...
> 2019-10-09T14:24:46.257Z - info: Finished Connecting to Database
> 2019-10-09T14:24:46.258Z - info: Initializing Stack...
> 2019-10-09T14:24:46.351Z - error:
> { message: 'Address already in use',
> stack: 'Error: Address already in use\n at Function.parseData (/root/backoffice-administration/node_modules/redis-server/RedisServer.js:167:22)\n at Socket.dataListener (/root/backoffice-administration/node_modules/redis-server/RedisServer.js:237:38)\n at emitOne (events.js:121:20)\n at Socket.emit (events.js:211:7)\n at addChunk (_stream_readable.js:263:12)\n at readableAddChunk (_stream_readable.js:250:11)\n at Socket.Readable.push (_stream_readable.js:208:10)\n at Pipe.onread (net.js:607:20)',
> code: -1 }
> 
> Can anybody help with this please? I have already changed the magoware port to several different ones but I still get this error.
> 
> Thanks

I Have the same problem of you did you resolve it?
