### ISSUE TITLE
Categories / Channels issues 

### ISSUE THREAD

**Issue by ritchieg9** [MAGOWARE/backoffice-administration#38]
After installing the application, when I select category the page is not opening, same as when I try to add a new channel 

error: Getting genre list failed with error:  message=ER_WRO
NG_FIELD_WITH_GROUP: Expression #5 of SELECT list is not in
GROUP BY clause and contains nonaggregated column 'magoware.
channels.id' which is not functionally dependent on columns
in GROUP BY clause; this is incompatible with sql_mode=only_
full_group_by, name=SequelizeDatabaseError, stack=SequelizeD
atabaseError: ER_WRONG_FIELD_WITH_GROUP: Expression #5 of SE
LECT list is not in GROUP BY clause and contains nonaggregat
ed column 'magoware.channels.id' which is not functionally d
ependent on columns in GROUP BY clause; this is incompatible
 with sql_mode=only_full_group_by
    at Query.formatError (/root/backoffice-administration/no
de_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query.<anonymous> (/root/backoffice-administration/no
de_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.<anonymous> (/root/backoffice-administration/no
de_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/root/backoffice-administration/node
_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/root/backoffice-administration/n
ode_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/root/backoffice-administration/no
de_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/root/backoffice-administratio
n/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/root/backoffice-administration/node_mo
dules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/backoffice-administration/node_
modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/root/backoffice-administration/n
ode_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/root/backoffice-administration/n
ode_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
From previous event:
    at Query.run (/root/backoffice-administration/node_modul
es/sequelize/lib/dialects/mysql/query.js:39:17)
    at /root/backoffice-administration/node_modules/sequeliz
e/lib/sequelize.js:849:20
    at /root/backoffice-administration/node_modules/retry-as
-promised/index.js:39:21
From previous event:
    at retryAsPromised (/root/backoffice-administration/node
_modules/retry-as-promised/index.js:29:10)
    at /root/backoffice-administration/node_modules/sequeliz
e/lib/sequelize.js:848:12
From previous event:
    at Promise.then (/root/backoffice-administration/node_mo
dules/sequelize/lib/promise.js:21:17)
    at Model.findAndCount (/root/backoffice-administration/n
ode_modules/sequelize/lib/model.js:1672:35)
    at exports.list (/root/backoffice-administration/modules
/mago/server/controllers/genre.server.controller.js:130:11)
    at Layer.handle [as handle_request] (/root/backoffice-ad
ministration/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/backoffice-administration/node_modules/ex
press/lib/router/route.js:137:13)
    at /root/backoffice-administration/modules/mago/server/p
olicies/mago.server.policy.js:69:20
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:6
17:5), code=ER_WRONG_FIELD_WITH_GROUP, errno=1055, sqlMessag
e=Expression #5 of SELECT list is not in GROUP BY clause and
 contains nonaggregated column 'magoware.channels.id' which
is not functionally dependent on columns in GROUP BY clause;
 this is incompatible with sql_mode=only_full_group_by, sqlS
tate=42000, index=0, sql=SELECT `genre`.`id`, `genre`.`descr
iption`, `genre`.`icon_url`, `genre`.`is_available`, `channe
ls`.`id` AS `channels.id`, count(`channels`.`id`) AS `channe
ls.total` FROM `genre` AS `genre` LEFT OUTER JOIN `channels`
 AS `channels` ON `genre`.`id` = `channels`.`genre_id` GROUP
 BY `genre`.`id`, `genre`.`description`;, $ref=$["parent"],
sql=SELECT `genre`.`id`, `genre`.`description`, `genre`.`ico
n_url`, `genre`.`is_available`, `channels`.`id` AS `channels
.id`, count(`channels`.`id`) AS `channels.total` FROM `genre
` AS `genre` LEFT OUTER JOIN `channels` AS `channels` ON `ge
nre`.`id` = `channels`.`genre_id` GROUP BY `genre`.`id`, `ge
nre`.`description`;, __stackCleaned__=true

**Comment by irisstaro** [comment]
Hello!

Please make sure the MySQL mode is set globally as 'NO_ENGINE_SUBSTITUTION' . This will resolve the issue you are facing

Regards
