### ISSUE TITLE
Can't create a new channel

### ISSUE THREAD

**Issue by PastaGringo** [MAGOWARE/backoffice-administration#39]
Hi,

The VPS config : 
Ubuntu Xenial
8 dedicated vCPU
32 GB RAM
50GB hard disk 
800 Mbps bandwith

I installed successfuly the back office without any issue ;)
Now I want to create a new channel but I have a weird issue : when I click on "Add", the blue loading bar appears and go on the right indefinitely but nothing on the page. I rebooted the application many times.

I used this command to see log from the app : `node server.js > my_app_log.log 2> my_app_err.log`

There is the APP logs : 

```
2019-02-21T16:55:39.105Z - verbose: Executing (default): SELECT `channels`.*, `packages_channels`.`id` AS `packages_channels.id`, `packages_channels`.`package_id` AS `packages_channels.package_id` FROM (SELECT `channels`.`id`, `channels`.`genre_id`, `channels`.`package_id`, `channels`.`channel_number`, `channels`.`epg_map_id`, `channels`.`title`, `channels`.`description`, `channels`.`icon_url`, `channels`.`pin_protected`, `channels`.`isavailable`, `channels`.`createdAt`, `channels`.`updatedAt`, `genre`.`id` AS `genre.id`, `genre`.`description` AS `genre.description`, `genre`.`is_available` AS `genre.is_available`, `genre`.`icon_url` AS `genre.icon_url`, `genre`.`createdAt` AS `genre.createdAt`, `genre`.`updatedAt` AS `genre.updatedAt` FROM `channels` AS `channels` INNER JOIN `genre` AS `genre` ON `channels`.`genre_id` = `genre`.`id` WHERE `channels`.`isavailable` = false ORDER BY channel_number ASC LIMIT 30) AS `channels` LEFT OUTER JOIN `packages_channels` AS `packages_channels` ON `channels`.`id` = `packages_channels`.`channel_id` ORDER BY channel_number ASC;
2019-02-21T16:55:39.131Z - verbose: Executing (default): SELECT count(`package`.`id`) AS `count` FROM `package` AS `package` INNER JOIN `package_type` AS `package_type` ON `package`.`package_type_id` = `package_type`.`id`;
2019-02-21T16:55:42.898Z - verbose: Executing (default): SELECT count(*) AS `count` FROM `channel_stream_source` AS `channel_stream_source`;
2019-02-21T16:55:42.903Z - verbose: Executing (default): SELECT `id`, `stream_source`, `createdAt`, `updatedAt` FROM `channel_stream_source` AS `channel_stream_source`;
2019-02-21T16:55:46.619Z - verbose: Executing (default): SELECT count(*) AS `count` FROM `channels` AS `channels`;
2019-02-21T16:55:46.625Z - verbose: Executing (default): SELECT `channels`.*, `packages_channels`.`id` AS `packages_channels.id`, `packages_channels`.`package_id` AS `packages_channels.package_id` FROM (SELECT `channels`.`id`, `channels`.`genre_id`, `channels`.`package_id`, `channels`.`channel_number`, `channels`.`epg_map_id`, `channels`.`title`, `channels`.`description`, `channels`.`icon_url`, `channels`.`pin_protected`, `channels`.`isavailable`, `channels`.`createdAt`, `channels`.`updatedAt`, `genre`.`id` AS `genre.id`, `genre`.`description` AS `genre.description`, `genre`.`is_available` AS `genre.is_available`, `genre`.`icon_url` AS `genre.icon_url`, `genre`.`createdAt` AS `genre.createdAt`, `genre`.`updatedAt` AS `genre.updatedAt` FROM `channels` AS `channels` INNER JOIN `genre` AS `genre` ON `channels`.`genre_id` = `genre`.`id` ORDER BY channel_number ASC LIMIT 30) AS `channels` LEFT OUTER JOIN `packages_channels` AS `packages_channels` ON `channels`.`id` = `packages_channels`.`channel_id` ORDER BY channel_number ASC;
2019-02-21T16:55:46.647Z - verbose: Executing (default): SELECT count(`package`.`id`) AS `count` FROM `package` AS `package` INNER JOIN `package_type` AS `package_type` ON `package`.`package_type_id` = `package_type`.`id`;
2019-02-21T16:55:47.554Z - verbose: Executing (default): SELECT count(`genre`.`id`) AS `count` FROM `genre` AS `genre` LEFT OUTER JOIN `channels` AS `channels` ON `genre`.`id` = `channels`.`genre_id` GROUP BY `genre`.`id`, `genre`.`description`;
2019-02-21T16:55:47.562Z - verbose: Executing (default): SELECT `genre`.`id`, `genre`.`description`, `genre`.`icon_url`, `genre`.`is_available`, `channels`.`id` AS `channels.id`, count(`channels`.`id`) AS `channels.total` FROM `genre` AS `genre` LEFT OUTER JOIN `channels` AS `channels` ON `genre`.`id` = `channels`.`genre_id` GROUP BY `genre`.`id`, `genre`.`description`;
2019-02-21T16:55:47.587Z - verbose: Executing (default): SELECT count(`package`.`id`) AS `count` FROM `package` AS `package` INNER JOIN `package_type` AS `package_type` ON `package`.`package_type_id` = `package_type`.`id` WHERE `package`.`package_type_id` IN ('1', '2');
```
And the ERR log : 

```
From previous event:
    at Promise.then (/home/XXXXXX/backoffice-administration/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAndCount (/home/XXXXXX/backoffice-administration/node_modules/sequelize/lib/model.js:1672:35)
    at exports.list (/home/XXXXXX/backoffice-administration/modules/mago/server/controllers/genre.server.controller.js:130:11)
    at Layer.handle [as handle_request] (/home/XXXXXX/backoffice-administration/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXXXXX/backoffice-administration/node_modules/express/lib/router/route.js:137:13)
    at /home/XXXXXX/backoffice-administration/modules/mago/server/policies/mago.server.policy.js:69:20
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5), code=ER_WRONG_FIELD_WITH_GROUP, errno=1055, sqlMessage=Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'MMS.channels.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by, sqlState=42000, index=0, sql=SELECT `genre`.`id`, `genre`.`description`, `genre`.`icon_url`, `genre`.`is_available`, `channels`.`id` AS `channels.id`, count(`channels`.`id`) AS `channels.total` FROM `genre` AS `genre` LEFT OUTER JOIN `channels` AS `channels` ON `genre`.`id` = `channels`.`genre_id` GROUP BY `genre`.`id`, `genre`.`description`;, $ref=$["parent"], sql=SELECT `genre`.`id`, `genre`.`description`, `genre`.`icon_url`, `genre`.`is_available`, `channels`.`id` AS `channels.id`, count(`channels`.`id`) AS `channels.total` FROM `genre` AS `genre` LEFT OUTER JOIN `channels` AS `channels` ON `genre`.`id` = `channels`.`genre_id` GROUP BY `genre`.`id`, `genre`.`description`;, __stackCleaned__=true
```

Do you have any ideas ?
Thanks !

**Comment by irisstaro** [comment]
Hello!

Please make sure MySQL mode is set globally to 'NO_ENGINE_SUBSTITUTION' to resolve the issue.

Regards

**Comment by PastaGringo** [comment]
Indeed, it's working now, thanks ! ;)

with the SQL command `set global sql_mode = 'NO_ENGINE_SUBSTITUTION';`
