### ISSUE TITLE
Missing Tables - Fresh Install - Fresh Database

### ISSUE THREAD

**Issue by drphipps** [MAGOWARE/backoffice-administration#67]
Unhandled rejection SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'magoware.settings' doesn't exist
    at Query.formatError (/home/alan/backoffice-administration/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query.<anonymous> (/home/alan/backoffice-administration/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.<anonymous> (/home/alan/backoffice-administration/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/home/alan/backoffice-administration/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/home/alan/backoffice-administration/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/alan/backoffice-administration/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/alan/backoffice-administration/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/alan/backoffice-administration/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/alan/backoffice-administration/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/alan/backoffice-administration/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/alan/backoffice-administration/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/alan/backoffice-administration/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
From previous event:
    at Query.run (/home/alan/backoffice-administration/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
    at /home/alan/backoffice-administration/node_modules/sequelize/lib/sequelize.js:849:20
    at /home/alan/backoffice-administration/node_modules/retry-as-promised/index.js:39:21
From previous event:
    at retryAsPromised (/home/alan/backoffice-administration/node_modules/retry-as-promised/index.js:29:10)
    at ConnectionManager.<anonymous> (/home/alan/backoffice-administration/node_modules/sequelize/lib/sequelize.js:848:12)
From previous event:
    at Promise.then (/home/alan/backoffice-administration/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/home/alan/backoffice-administration/node_modules/sequelize/lib/model.js:1395:6)
    at Object.exports.invokeRolesPolicies (/home/alan/backoffice-administration/modules/mago/server/policies/mago.server.policy.js:31:17)
    at /home/alan/backoffice-administration/config/lib/express.js:251:43
    at Array.forEach (<anonymous>)
    at Object.module.exports.initModulesServerPolicies (/home/alan/backoffice-administration/config/lib/express.js:250:34)
    at Object.module.exports.init (/home/alan/backoffice-administration/config/lib/express.js:402:10)
    at /home/alan/backoffice-administration/config/lib/app.js:29:21
    at server.open (/home/alan/backoffice-administration/config/lib/redis.js:105:13)
    at promise.then (/home/alan/backoffice-administration/node_modules/redis-server/RedisServer.js:413:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by eduardhasanaj2** [comment]
Hi @drphipps 
A major update is on the way.
Soon it will be approved and published in repository.
