### ISSUE TITLE
Redis-Server not available

### ISSUE THREAD

**Issue by Ipasya** [MAGOWARE/backoffice-administration#71]
My Node Js doesn't have Module Redis-Server and maybe another module, how to complete install module node? I stack on it. Thank You

**Comment by eduardhasanaj2** [comment]
Hi @Ipasya 
Please read our guide carefully. It is required to write following command to install modules
`npm install`
I am closing this but if the fix  suggested does not solve it we can reopen it.
Best regards

**Comment by Ipasya** [comment]
But the redis-server module failed to install, and i can't still run 'Sudo node server.js', i've tried npm install, and the error same, "Error: Cannot find module 'redis-server'"

**Comment by eduardhasanaj2** [comment]
@Ipasya please paste full error details here

**Comment by Ipasya** [comment]
This is Error :
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/eduardhasanaj2/node-redis-server.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-15T01_44_17_088Z-debug.log

Can you help me?

**Comment by Ipasya** [comment]
And if I start Server.js, this is the error:
sudo node server.js
-------------------------------------Starting server----------------------------------------------------
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'redis-server'
Require stack:
- /etc/magoware/config/lib/redis.js
- /etc/magoware/modules/mago/server/policies/mago.server.policy.js
- /etc/magoware/config/lib/express.js
- /etc/magoware/config/lib/app.js
- /etc/magoware/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/etc/magoware/config/lib/redis.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/etc/magoware/modules/mago/server/policies/mago.server.policy.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/etc/magoware/config/lib/redis.js',
    '/etc/magoware/modules/mago/server/policies/mago.server.policy.js',
    '/etc/magoware/config/lib/express.js',
    '/etc/magoware/config/lib/app.js',
    '/etc/magoware/server.js'
  ]
}

I Stuck in this step, any solution?

**Comment by yamcell** [comment]
Yes u can pay installed fee magoware offer cheap price

**Comment by Ipasya** [comment]
> Yes u can pay installed fee magoware offer cheap price

I want try to do it by my self, interest to learn it

**Comment by irisstaro** [comment]
Hello @Ipasya 
Are you doing a fresh installation or an update?
Can you specify the node an npm version you are using?

**Comment by eduardhasanaj2** [comment]
Hi @Ipasya 
Sorry for the delay!
You need to install git in your server

**Comment by Ipasya** [comment]
> Hi @Ipasya
> Sorry for the delay
> You need to install git in your server

This Work for me, and now i  face up to new problem. thanks guys. I Try to solve my prblem by my self first
