### ISSUE TITLE
Fresh Install - Error Table 'magoware.settings' doesn't exist

### ISSUE THREAD

**Issue by kalhori124** [MAGOWARE/backoffice-administration#80]
Hi, I installed MangoWare though https://magoware.freshdesk.com/support/solutions/articles/35000124356 but I got this error 

Unhandled rejection SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'magoware.settings' doesn't exist
    at Query.formatError (/opt/magoware/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query.<anonymous> (/opt/magoware/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.<anonymous> (/opt/magoware/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/opt/magoware/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/opt/magoware/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/opt/magoware/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/opt/magoware/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/opt/magoware/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/opt/magoware/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/opt/magoware/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/opt/magoware/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/opt/magoware/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
From previous event:
    at Query.run (/opt/magoware/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
    at /opt/magoware/node_modules/sequelize/lib/sequelize.js:849:20
    at /opt/magoware/node_modules/retry-as-promised/index.js:39:21
From previous event:
    at retryAsPromised (/opt/magoware/node_modules/retry-as-promised/index.js:29:10)
    at ConnectionManager.<anonymous> (/opt/magoware/node_modules/sequelize/lib/sequelize.js:848:12)
From previous event:
    at Promise.then (/opt/magoware/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/opt/magoware/node_modules/sequelize/lib/model.js:1395:6)
    at Object.exports.invokeRolesPolicies (/opt/magoware/modules/mago/server/policies/mago.server.policy.js:31:17)
    at /opt/magoware/config/lib/express.js:251:43
    at Array.forEach (<anonymous>)
    at Object.module.exports.initModulesServerPolicies (/opt/magoware/config/lib/express.js:250:34)
    at Object.module.exports.init (/opt/magoware/config/lib/express.js:402:10)
    at /opt/magoware/config/lib/app.js:29:21
    at server.open (/opt/magoware/config/lib/redis.js:105:13)
    at promise.then (/opt/magoware/node_modules/redis-server/RedisServer.js:413:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by irisstaro** [comment]
Hello @kalhori124 
Yes, that error is shown only the first time the management system is run till the database is fully populated. 
The error does not prevent the management system to be installed

Regards
Iris
