### ISSUE TITLE
error: Root company creation failed with error:  message=user.makeSalt is not a function, stack=TypeError: user.makeSalt is not a function

### ISSUE THREAD

**Issue by johanjpk** [MAGOWARE/backoffice-administration#87]
When I start the server I get the following error: 
`error: Root company creation failed with error:  message=user.makeSalt is not a function, stack=TypeError: user.makeSalt is not a function`

Dont know where to look. Complete error message is: 
`error: Root company creation failed with error:  message=user.makeSalt is not a function, stack=TypeError: user.makeSalt is not a function
    at /home/johan/backoffice-administration/custom_functions/company.js:219:50
From previous event:
    at /home/johan/backoffice-administration/custom_functions/company.js:216:90
From previous event:
    at /home/johan/backoffice-administration/custom_functions/company.js:215:99
From previous event:
    at /home/johan/backoffice-administration/custom_functions/company.js:214:99
From previous event:
    at /home/johan/backoffice-administration/custom_functions/company.js:200:76
    at transaction.prepareEnvironment.then (/home/johan/backoffice-administration/node_modules/sequelize/lib/sequelize.js:969:21)
From previous event:
    at Sequelize._clsRun (/home/johan/backoffice-administration/node_modules/sequelize/lib/sequelize.js:969:10)
    at Function._clsRun (/home/johan/backoffice-administration/node_modules/sequelize/lib/sequelize.js:1013:21)
    at Sequelize.transaction (/home/johan/backoffice-administration/node_modules/sequelize/lib/sequelize.js:967:22)
    at /home/johan/backoffice-administration/custom_functions/company.js:199:42
From previous event:
    at /home/johan/backoffice-administration/custom_functions/company.js:185:12
    at new Promise (<anonymous>)
    at Object.exports.createRootCompany (/home/johan/backoffice-administration/custom_functions/company.js:182:12)
    at /home/johan/backoffice-administration/config/lib/sequelize.js:59:46
    at nextTask (/home/johan/backoffice-administration/node_modules/async/dist/async.js:4578:27)
    at Object.waterfall (/home/johan/backoffice-administration/node_modules/async/dist/async.js:4589:9)
    at Object.awaitable(waterfall) [as waterfall] (/home/johan/backoffice-administration/node_modules/async/dist/async.js:208:32)
    at /home/johan/backoffice-administration/config/lib/sequelize.js:56:27
From previous event:
    at /home/johan/backoffice-administration/config/lib/sequelize.js:55:18
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.db.connect (/home/johan/backoffice-administration/config/lib/sequelize.js:41:30)
    at Object.<anonymous> (/home/johan/backoffice-administration/config/lib/sequelize-connect.js:22:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/johan/backoffice-administration/config/lib/app.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/johan/backoffice-administration/server.js:94:15
    at wrapper (/home/johan/backoffice-administration/node_modules/async/dist/async.js:272:20)
    at next (/home/johan/backoffice-administration/node_modules/async/dist/async.js:4584:24)
    at /home/johan/backoffice-administration/node_modules/async/dist/async.js:325:20
    at /home/johan/backoffice-administration/server.js:89:9
    at nextTask (/home/johan/backoffice-administration/node_modules/async/dist/async.js:4578:27)
    at next (/home/johan/backoffice-administration/node_modules/async/dist/async.js:4586:13)
    at /home/johan/backoffice-administration/node_modules/async/dist/async.js:325:20, __stackCleaned__=true`

**Comment by johanjpk** [comment]
Starting again from scratch solved the issue. Removing the folder and cloned again. and then it worked.
