### ISSUE TITLE
Error Company settings

### ISSUE THREAD

**Issue by hkaiser01** [MAGOWARE/backoffice-administration#90]
Hi,

I installed Magoware and everthing seems to work, only the company settings can not be set.

Gettig this error when I am logged in as superadmin:
2020-02-03T06:29:57.454Z - error: TypeError: Cannot read property 'company_name' of undefined
    at exports.env_settings (/var/www/backoffice-administration/modules/mago/server/controllers/settings.server.controller.js:59:68)
    at Layer.handle [as handle_request] (/var/www/backoffice-administration/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/backoffice-administration/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/backoffice-administration/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/backoffice-administration/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/backoffice-administration/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/backoffice-administration/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/backoffice-administration/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/var/www/backoffice-administration/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:198:13)
    at SendStream.error (/var/www/backoffice-administration/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/var/www/backoffice-administration/node_modules/send/index.js:421:12)
    at next (/var/www/backoffice-administration/node_modules/send/index.js:735:16)
    at onstat (/var/www/backoffice-administration/node_modules/send/index.js:724:14)
    at FSReqWrap.oncomplete (fs.js:153:21)

What can I do? Thanks for your help.

HK

**Comment by hkaiser01** [comment]
The error changed now.

GET /api/company_settings_list_company_data/-1 - - - - ms
2020-09-13T16:56:16.814Z - verbose: Executing (default): select * from (select s.company_name, COUNT(u.id) as total_accounts, u.company_id as id from users u inner join settings s on s.id = u.company_id group by u.company_id)as b UNION ALL select * from (SELECT s.company_name, 0 , s.id FROM settings s LEFT OUTER JOIN users u ON s.id = u.company_id WHERE u.company_id IS NULL )a  order by company_name
2020-09-13T16:56:16.817Z - verbose: Executing (default): select * from (select s.company_name, COUNT(ch.id) as total_channels, ch.company_id as id from channels ch inner join settings s on s.id = ch.company_id group by ch.company_id)as b UNION ALL select * from (SELECT s.company_name, 0, s.id FROM settings s LEFT OUTER JOIN channels ch ON s.id = ch.company_id WHERE ch.company_id IS NULL)  a order by company_name
2020-09-13T16:56:16.818Z - verbose: Executing (default): select * from (select s.company_name, COUNT(v.id) as total_vod, v.company_id as id from vod v inner join settings s on s.id = v.company_id group by v.company_id)as b UNION ALL select * from (SELECT s.company_name, 0, s.id FROM settings s LEFT OUTER JOIN vod v ON s.id = v.company_id WHERE v.company_id IS NULL) a order by company_name
2020-09-13T16:56:16.818Z - verbose: Executing (default): select * from (select s.company_name, COUNT(am.id) as total_assets, am.company_id as id from assets_master am inner join settings s on s.id = am.company_id group by am.company_id)as b  UNION ALL select * from (SELECT s.company_name, 0, s.id FROM settings s LEFT OUTER JOIN assets_master am ON s.id = am.company_id WHERE am.company_id IS NULL)a order by company_name
error: Failed getting all assets list data No data found

I am logging in as superadmin, want to add a company. I'm getting the error above. What can I do?

with best regards
HK
